image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  github:
    artifacts:
    - release
    repo: csvlint
    script:
    - make release
    tag: v$(cat VERSION)
    token: $$github_token
    user: Clever
    when:
      branch: master
  report_card: {}
script:
- make test
