apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: csvlint
  description: library and command line tool that validates a CSV file
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
